#include<iostream>
#include<vector>
#include<memory>
#include<gmp.h>
#include<gmpxx.h>
#include<mpfr.h>
#include<chrono>
#include"boost/multi_array.hpp"
#include<string>
#include<filesystem>
#include"utils/utils.hpp"
#include"potentials/potentials.hpp"
#include"walker.hpp"